#!/bin/bash

#$ -P bf528
#$ -cwd
#$ -pe omp 2
#$ -j y
#$ -o /projectnb2/bf528/users/saxophone/data_p4/qsub_output

source /etc/bashrc

## Feeds each .fastq.gz to python counter script line by line, and outputs
## the counts to a pickle file for further analysis

## This version concatenates all the sources together to a single lumped output

module load python3/3.8.10

# /projectnb/bf528/project_4_scrnaseq/fastq/SRR3879604/SRR3879604_1_bc.fastq.gz

source_dir="/projectnb/bf528/project_4_scrnaseq/fastq"
output_dir="/projectnb2/bf528/users/saxophone/data_p4/fastq_bc"

sources=""

for sample in SRR3879604 SRR3879605 SRR3879606
do
  zipped=${source_dir}/${sample}/${sample}_1_bc.fastq.gz
  sources+=" ${zipped}"
done

zcat $sources | ./count_barcodes.py ${output_dir}/lumped.pickle
