#!/bin/bash

#$ -P bf528
#$ -cwd
#$ -pe omp 3
#$ -j y
#$ -o /projectnb2/bf528/users/saxophone/data_p4/qsub_output

source /etc/bashrc

# Unzips the fastq files with barcodes into the target directory.
# NOTE: this currently yells at you for using up too much memory.

# /projectnb/bf528/project_4_scrnaseq/fastq/SRR3879604/SRR3879604_1_bc.fastq.gz

source_dir="/projectnb/bf528/project_4_scrnaseq/fastq"
output_dir="/projectnb2/bf528/users/saxophone/data_p4/fastq_bc"

for sample in SRR3879604 SRR3879605 SRR3879606
do
  zipped=${source_dir}/${sample}/${sample}_1_bc.fastq.gz
  #zcat $zipped | head -n 4000 > ${output_dir}/${sample}_1_bc_test.fastq & # Test w/ first 1000 reads
  zcat $zipped > ${output_dir}/${sample}_1_bc.fastq & # For real this time
done

wait
